function getEmergencyData() {
    const data = [
      {
        "geometry":{
          "coordinates":[
            35.233333,
            31.766666666666666
          ],
          "type":"Point"
        },
        "properties":{
          "city":"Palestine",
          "count":30,
          "deaths":0,
          "description":"<strong>Palestine</strong><p>Incidents: 30<br>Deaths: 0</p>",
          "icon":"theatre"
        },
        "type":"Feature"
      },
      {
        "geometry":{
          "coordinates":[
            69.183333,
            34.516666666666666
          ],
          "type":"Point"
        },
        "properties":{
          "city":"Afghanistan",
          "count":7,
          "deaths":0,
          "description":"<strong>Afghanistan</strong><p>Incidents: 7<br>Deaths: 0</p>",
          "icon":"theatre"
        },
        "type":"Feature"
      },
      {
        "geometry":{
          "coordinates":[
            19.816667,
            41.31666666666667
          ],
          "type":"Point"
        },
        "properties":{
          "city":"Albania",
          "count":23,
          "deaths":1,
          "description":"<strong>Albania</strong><p>Incidents: 23<br>Deaths: 1</p>",
          "icon":"theatre"
        },
        "type":"Feature"
      },
      {
        "geometry":{
          "coordinates":[
            3.05,
            36.75
          ],
          "type":"Point"
        },
        "properties":{
          "city":"Algeria",
          "count":24,
          "deaths":1,
          "description":"<strong>Algeria</strong><p>Incidents: 24<br>Deaths: 1</p>",
          "icon":"theatre"
        },
        "type":"Feature"
      },
      {
        "geometry":{
          "coordinates":[
            1.516667,
            42.5
          ],
          "type":"Point"
        },
        "properties":{
          "city":"Andorra",
          "count":1,
          "deaths":0,
          "description":"<strong>Andorra</strong><p>Incidents: 1<br>Deaths: 0</p>",
          "icon":"theatre"
        },
        "type":"Feature"
      },
      {
        "geometry":{
          "coordinates":[
            -58.666667,
            -34.583333333333336
          ],
          "type":"Point"
        },
        "properties":{
          "city":"Argentina",
          "count":31,
          "deaths":1,
          "description":"<strong>Argentina</strong><p>Incidents: 31<br>Deaths: 1</p>",
          "icon":"theatre"
        },
        "type":"Feature"
      },
      {
        "geometry":{
          "coordinates":[
            44.5,
            40.166666666666664
          ],
          "type":"Point"
        },
        "properties":{
          "city":"Armenia",
          "count":6,
          "deaths":0,
          "description":"<strong>Armenia</strong><p>Incidents: 6<br>Deaths: 0</p>",
          "icon":"theatre"
        },
        "type":"Feature"
      },
      {
        "geometry":{
          "coordinates":[
            149.133333,
            -35.266666666666666
          ],
          "type":"Point"
        },
        "properties":{
          "city":"Australia",
          "count":156,
          "deaths":3,
          "description":"<strong>Australia</strong><p>Incidents: 156<br>Deaths: 3</p>",
          "icon":"theatre"
        },
        "type":"Feature"
      },
      {
        "geometry":{
          "coordinates":[
            16.366667,
            48.2
          ],
          "type":"Point"
        },
        "properties":{
          "city":"Austria",
          "count":361,
          "deaths":1,
          "description":"<strong>Austria</strong><p>Incidents: 361<br>Deaths: 1</p>",
          "icon":"theatre"
        },
        "type":"Feature"
      },
      {
        "geometry":{
          "coordinates":[
            49.866667,
            40.38333333333333
          ],
          "type":"Point"
        },
        "properties":{
          "city":"Azerbaijan",
          "count":13,
          "deaths":0,
          "description":"<strong>Azerbaijan</strong><p>Incidents: 13<br>Deaths: 0</p>",
          "icon":"theatre"
        },
        "type":"Feature"
      },
      {
        "geometry":{
          "coordinates":[
            50.566667,
            26.233333333333334
          ],
          "type":"Point"
        },
        "properties":{
          "city":"Bahrain",
          "count":162,
          "deaths":0,
          "description":"<strong>Bahrain</strong><p>Incidents: 162<br>Deaths: 0</p>",
          "icon":"theatre"
        },
        "type":"Feature"
      },
      {
        "geometry":{
          "coordinates":[
            90.4,
            23.716666666666665
          ],
          "type":"Point"
        },
        "properties":{
          "city":"Bangladesh",
          "count":3,
          "deaths":0,
          "description":"<strong>Bangladesh</strong><p>Incidents: 3<br>Deaths: 0</p>",
          "icon":"theatre"
        },
        "type":"Feature"
      },
      {
        "geometry":{
          "coordinates":[
            27.566667,
            53.9
          ],
          "type":"Point"
        },
        "properties":{
          "city":"Belarus",
          "count":21,
          "deaths":0,
          "description":"<strong>Belarus</strong><p>Incidents: 21<br>Deaths: 0</p>",
          "icon":"theatre"
        },
        "type":"Feature"
      },
      {
        "geometry":{
          "coordinates":[
            4.333333,
            50.833333333333336
          ],
          "type":"Point"
        },
        "properties":{
          "city":"Belgium",
          "count":399,
          "deaths":3,
          "description":"<strong>Belgium</strong><p>Incidents: 399<br>Deaths: 3</p>",
          "icon":"theatre"
        },
        "type":"Feature"
      },
      {
        "geometry":{
          "coordinates":[
            89.633333,
            27.466666666666665
          ],
          "type":"Point"
        },
        "properties":{
          "city":"Bhutan",
          "count":1,
          "deaths":0,
          "description":"<strong>Bhutan</strong><p>Incidents: 1<br>Deaths: 0</p>",
          "icon":"theatre"
        },
        "type":"Feature"
      },
      {
        "geometry":{
          "coordinates":[
            -68.15,
            -16.5
          ],
          "type":"Point"
        },
        "properties":{
          "city":"Bolivia",
          "count":3,
          "deaths":0,
          "description":"<strong>Bolivia</strong><p>Incidents: 3<br>Deaths: 0</p>",
          "icon":"theatre"
        },
        "type":"Feature"
      },
      {
        "geometry":{
          "coordinates":[
            18.416667,
            43.86666666666667
          ],
          "type":"Point"
        },
        "properties":{
          "city":"Bosnia and Herzegovina",
          "count":11,
          "deaths":0,
          "description":"<strong>Bosnia and Herzegovina</strong><p>Incidents: 11<br>Deaths: 0</p>",
          "icon":"theatre"
        },
        "type":"Feature"
      },
      {
        "geometry":{
          "coordinates":[
            -47.916667,
            -15.783333333333333
          ],
          "type":"Point"
        },
        "properties":{
          "city":"Brazil",
          "count":77,
          "deaths":0,
          "description":"<strong>Brazil</strong><p>Incidents: 77<br>Deaths: 0</p>",
          "icon":"theatre"
        },
        "type":"Feature"
      },
      {
        "geometry":{
          "coordinates":[
            114.933333,
            4.883333333333333
          ],
          "type":"Point"
        },
        "properties":{
          "city":"Brunei Darussalam",
          "count":25,
          "deaths":0,
          "description":"<strong>Brunei Darussalam</strong><p>Incidents: 25<br>Deaths: 0</p>",
          "icon":"theatre"
        },
        "type":"Feature"
      },
      {
        "geometry":{
          "coordinates":[
            23.316667,
            42.68333333333333
          ],
          "type":"Point"
        },
        "properties":{
          "city":"Bulgaria",
          "count":23,
          "deaths":1,
          "description":"<strong>Bulgaria</strong><p>Incidents: 23<br>Deaths: 1</p>",
          "icon":"theatre"
        },
        "type":"Feature"
      },
      {
        "geometry":{
          "coordinates":[
            -1.516667,
            12.366666666666667
          ],
          "type":"Point"
        },
        "properties":{
          "city":"Burkina Faso",
          "count":2,
          "deaths":0,
          "description":"<strong>Burkina Faso</strong><p>Incidents: 2<br>Deaths: 0</p>",
          "icon":"theatre"
        },
        "type":"Feature"
      },
      {
        "geometry":{
          "coordinates":[
            104.916667,
            11.55
          ],
          "type":"Point"
        },
        "properties":{
          "city":"Cambodia",
          "count":5,
          "deaths":0,
          "description":"<strong>Cambodia</strong><p>Incidents: 5<br>Deaths: 0</p>",
          "icon":"theatre"
        },
        "type":"Feature"
      },
      {
        "geometry":{
          "coordinates":[
            11.516667,
            3.8666666666666667
          ],
          "type":"Point"
        },
        "properties":{
          "city":"Cameroon",
          "count":2,
          "deaths":0,
          "description":"<strong>Cameroon</strong><p>Incidents: 2<br>Deaths: 0</p>",
          "icon":"theatre"
        },
        "type":"Feature"
      },
      {
        "geometry":{
          "coordinates":[
            -75.7,
            45.416666666666664
          ],
          "type":"Point"
        },
        "properties":{
          "city":"Canada",
          "count":138,
          "deaths":1,
          "description":"<strong>Canada</strong><p>Incidents: 138<br>Deaths: 1</p>",
          "icon":"theatre"
        },
        "type":"Feature"
      },
      {
        "geometry":{
          "coordinates":[
            -70.666667,
            -33.45
          ],
          "type":"Point"
        },
        "properties":{
          "city":"Chile",
          "count":33,
          "deaths":0,
          "description":"<strong>Chile</strong><p>Incidents: 33<br>Deaths: 0</p>",
          "icon":"theatre"
        },
        "type":"Feature"
      },
      {
        "geometry":{
          "coordinates":[
            116.383333,
            39.916666666666664
          ],
          "type":"Point"
        },
        "properties":{
          "city":"China",
          "count":80954,
          "deaths":3179,
          "description":"<strong>China</strong><p>Incidents: 80954<br>Deaths: 3179</p>",
          "icon":"theatre"
        },
        "type":"Feature"
      },
      {
        "geometry":{
          "coordinates":[
            -74.083333,
            4.6
          ],
          "type":"Point"
        },
        "properties":{
          "city":"Colombia",
          "count":9,
          "deaths":0,
          "description":"<strong>Colombia</strong><p>Incidents: 9<br>Deaths: 0</p>",
          "icon":"theatre"
        },
        "type":"Feature"
      },
      {
        "geometry":{
          "coordinates":[
            15.3,
            -4.316666666666666
          ],
          "type":"Point"
        },
        "properties":{
          "city":"Democratic Republic of the Congo",
          "count":1,
          "deaths":0,
          "description":"<strong>Democratic Republic of the Congo</strong><p>Incidents: 1<br>Deaths: 0</p>",
          "icon":"theatre"
        },
        "type":"Feature"
      },
      {
        "geometry":{
          "coordinates":[
            -84.083333,
            9.933333333333334
          ],
          "type":"Point"
        },
        "properties":{
          "city":"Costa Rica",
          "count":23,
          "deaths":0,
          "description":"<strong>Costa Rica</strong><p>Incidents: 23<br>Deaths: 0</p>",
          "icon":"theatre"
        },
        "type":"Feature"
      },
      {
        "geometry":{
          "coordinates":[
            16.0,
            45.8
          ],
          "type":"Point"
        },
        "properties":{
          "city":"Croatia",
          "count":25,
          "deaths":0,
          "description":"<strong>Croatia</strong><p>Incidents: 25<br>Deaths: 0</p>",
          "icon":"theatre"
        },
        "type":"Feature"
      },
      {
        "geometry":{
          "coordinates":[
            -82.35,
            23.116666666666667
          ],
          "type":"Point"
        },
        "properties":{
          "city":"Cuba",
          "count":3,
          "deaths":0,
          "description":"<strong>Cuba</strong><p>Incidents: 3<br>Deaths: 0</p>",
          "icon":"theatre"
        },
        "type":"Feature"
      },
      {
        "geometry":{
          "coordinates":[
            33.366667,
            35.166666666666664
          ],
          "type":"Point"
        },
        "properties":{
          "city":"Cyprus",
          "count":6,
          "deaths":0,
          "description":"<strong>Cyprus</strong><p>Incidents: 6<br>Deaths: 0</p>",
          "icon":"theatre"
        },
        "type":"Feature"
      },
      {
        "geometry":{
          "coordinates":[
            14.466667,
            50.083333333333336
          ],
          "type":"Point"
        },
        "properties":{
          "city":"Czech Republic",
          "count":63,
          "deaths":0,
          "description":"<strong>Czech Republic</strong><p>Incidents: 63<br>Deaths: 0</p>",
          "icon":"theatre"
        },
        "type":"Feature"
      },
      {
        "geometry":{
          "coordinates":[
            12.583333,
            55.666666666666664
          ],
          "type":"Point"
        },
        "properties":{
          "city":"Denmark",
          "count":676,
          "deaths":0,
          "description":"<strong>Denmark</strong><p>Incidents: 676<br>Deaths: 0</p>",
          "icon":"theatre"
        },
        "type":"Feature"
      },
      {
        "geometry":{
          "coordinates":[
            -69.9,
            18.466666666666665
          ],
          "type":"Point"
        },
        "properties":{
          "city":"Dominican Republic",
          "count":5,
          "deaths":0,
          "description":"<strong>Dominican Republic</strong><p>Incidents: 5<br>Deaths: 0</p>",
          "icon":"theatre"
        },
        "type":"Feature"
      },
      {
        "geometry":{
          "coordinates":[
            -78.5,
            -0.21666666666666667
          ],
          "type":"Point"
        },
        "properties":{
          "city":"Ecuador",
          "count":17,
          "deaths":0,
          "description":"<strong>Ecuador</strong><p>Incidents: 17<br>Deaths: 0</p>",
          "icon":"theatre"
        },
        "type":"Feature"
      },
      {
        "geometry":{
          "coordinates":[
            31.25,
            30.05
          ],
          "type":"Point"
        },
        "properties":{
          "city":"Egypt",
          "count":80,
          "deaths":2,
          "description":"<strong>Egypt</strong><p>Incidents: 80<br>Deaths: 2</p>",
          "icon":"theatre"
        },
        "type":"Feature"
      },
      {
        "geometry":{
          "coordinates":[
            24.716667,
            59.43333333333333
          ],
          "type":"Point"
        },
        "properties":{
          "city":"Estonia",
          "count":27,
          "deaths":0,
          "description":"<strong>Estonia</strong><p>Incidents: 27<br>Deaths: 0</p>",
          "icon":"theatre"
        },
        "type":"Feature"
      },
      {
        "geometry":{
          "coordinates":[
            24.933333,
            60.166666666666664
          ],
          "type":"Point"
        },
        "properties":{
          "city":"Finland",
          "count":155,
          "deaths":0,
          "description":"<strong>Finland</strong><p>Incidents: 155<br>Deaths: 0</p>",
          "icon":"theatre"
        },
        "type":"Feature"
      },
      {
        "geometry":{
          "coordinates":[
            2.333333,
            48.86666666666667
          ],
          "type":"Point"
        },
        "properties":{
          "city":"France",
          "count":2876,
          "deaths":61,
          "description":"<strong>France</strong><p>Incidents: 2876<br>Deaths: 61</p>",
          "icon":"theatre"
        },
        "type":"Feature"
      },
      {
        "geometry":{
          "coordinates":[
            9.45,
            0.38333333333333336
          ],
          "type":"Point"
        },
        "properties":{
          "city":"Gabon",
          "count":1,
          "deaths":0,
          "description":"<strong>Gabon</strong><p>Incidents: 1<br>Deaths: 0</p>",
          "icon":"theatre"
        },
        "type":"Feature"
      },
      {
        "geometry":{
          "coordinates":[
            44.833333,
            41.68333333333333
          ],
          "type":"Point"
        },
        "properties":{
          "city":"Georgia",
          "count":25,
          "deaths":0,
          "description":"<strong>Georgia</strong><p>Incidents: 25<br>Deaths: 0</p>",
          "icon":"theatre"
        },
        "type":"Feature"
      },
      {
        "geometry":{
          "coordinates":[
            13.4,
            52.516666666666666
          ],
          "type":"Point"
        },
        "properties":{
          "city":"Germany",
          "count":2369,
          "deaths":5,
          "description":"<strong>Germany</strong><p>Incidents: 2369<br>Deaths: 5</p>",
          "icon":"theatre"
        },
        "type":"Feature"
      },
      {
        "geometry":{
          "coordinates":[
            -0.216667,
            5.55
          ],
          "type":"Point"
        },
        "properties":{
          "city":"Ghana",
          "count":2,
          "deaths":0,
          "description":"<strong>Ghana</strong><p>Incidents: 2<br>Deaths: 0</p>",
          "icon":"theatre"
        },
        "type":"Feature"
      },
      {
        "geometry":{
          "coordinates":[
            23.733333,
            37.983333333333334
          ],
          "type":"Point"
        },
        "properties":{
          "city":"Greece",
          "count":133,
          "deaths":1,
          "description":"<strong>Greece</strong><p>Incidents: 133<br>Deaths: 1</p>",
          "icon":"theatre"
        },
        "type":"Feature"
      },
      {
        "geometry":{
          "coordinates":[
            -58.15,
            6.8
          ],
          "type":"Point"
        },
        "properties":{
          "city":"Guyana",
          "count":1,
          "deaths":1,
          "description":"<strong>Guyana</strong><p>Incidents: 1<br>Deaths: 1</p>",
          "icon":"theatre"
        },
        "type":"Feature"
      },
      {
        "geometry":{
          "coordinates":[
            -87.216667,
            14.1
          ],
          "type":"Point"
        },
        "properties":{
          "city":"Honduras",
          "count":2,
          "deaths":0,
          "description":"<strong>Honduras</strong><p>Incidents: 2<br>Deaths: 0</p>",
          "icon":"theatre"
        },
        "type":"Feature"
      },
      {
        "geometry":{
          "coordinates":[
            19.083333,
            47.5
          ],
          "type":"Point"
        },
        "properties":{
          "city":"Hungary",
          "count":16,
          "deaths":0,
          "description":"<strong>Hungary</strong><p>Incidents: 16<br>Deaths: 0</p>",
          "icon":"theatre"
        },
        "type":"Feature"
      },
      {
        "geometry":{
          "coordinates":[
            -21.95,
            64.15
          ],
          "type":"Point"
        },
        "properties":{
          "city":"Iceland",
          "count":117,
          "deaths":0,
          "description":"<strong>Iceland</strong><p>Incidents: 117<br>Deaths: 0</p>",
          "icon":"theatre"
        },
        "type":"Feature"
      },
      {
        "geometry":{
          "coordinates":[
            77.2,
            28.6
          ],
          "type":"Point"
        },
        "properties":{
          "city":"India",
          "count":75,
          "deaths":1,
          "description":"<strong>India</strong><p>Incidents: 75<br>Deaths: 1</p>",
          "icon":"theatre"
        },
        "type":"Feature"
      },
      {
        "geometry":{
          "coordinates":[
            106.816667,
            -6.166666666666667
          ],
          "type":"Point"
        },
        "properties":{
          "city":"Indonesia",
          "count":34,
          "deaths":1,
          "description":"<strong>Indonesia</strong><p>Incidents: 34<br>Deaths: 1</p>",
          "icon":"theatre"
        },
        "type":"Feature"
      },
      {
        "geometry":{
          "coordinates":[
            51.416667,
            35.7
          ],
          "type":"Point"
        },
        "properties":{
          "city":"Iran",
          "count":10075,
          "deaths":429,
          "description":"<strong>Iran</strong><p>Incidents: 10075<br>Deaths: 429</p>",
          "icon":"theatre"
        },
        "type":"Feature"
      },
      {
        "geometry":{
          "coordinates":[
            44.4,
            33.333333333333336
          ],
          "type":"Point"
        },
        "properties":{
          "city":"Iraq",
          "count":74,
          "deaths":8,
          "description":"<strong>Iraq</strong><p>Incidents: 74<br>Deaths: 8</p>",
          "icon":"theatre"
        },
        "type":"Feature"
      },
      {
        "geometry":{
          "coordinates":[
            -6.233333,
            53.31666666666667
          ],
          "type":"Point"
        },
        "properties":{
          "city":"Ireland",
          "count":70,
          "deaths":1,
          "description":"<strong>Ireland</strong><p>Incidents: 70<br>Deaths: 1</p>",
          "icon":"theatre"
        },
        "type":"Feature"
      },
      {
        "geometry":{
          "coordinates":[
            35.233333,
            31.766666666666666
          ],
          "type":"Point"
        },
        "properties":{
          "city":"Israel",
          "count":96,
          "deaths":0,
          "description":"<strong>Israel</strong><p>Incidents: 96<br>Deaths: 0</p>",
          "icon":"theatre"
        },
        "type":"Feature"
      },
      {
        "geometry":{
          "coordinates":[
            12.483333,
            41.9
          ],
          "type":"Point"
        },
        "properties":{
          "city":"Italy",
          "count":15113,
          "deaths":1016,
          "description":"<strong>Italy</strong><p>Incidents: 15113<br>Deaths: 1016</p>",
          "icon":"theatre"
        },
        "type":"Feature"
      },
      {
        "geometry":{
          "coordinates":[
            -76.8,
            18.0
          ],
          "type":"Point"
        },
        "properties":{
          "city":"Jamaica",
          "count":6,
          "deaths":0,
          "description":"<strong>Jamaica</strong><p>Incidents: 6<br>Deaths: 0</p>",
          "icon":"theatre"
        },
        "type":"Feature"
      },
      {
        "geometry":{
          "coordinates":[
            139.75,
            35.68333333333333
          ],
          "type":"Point"
        },
        "properties":{
          "city":"Japan",
          "count":675,
          "deaths":19,
          "description":"<strong>Japan</strong><p>Incidents: 675<br>Deaths: 19</p>",
          "icon":"theatre"
        },
        "type":"Feature"
      },
      {
        "geometry":{
          "coordinates":[
            35.933333,
            31.95
          ],
          "type":"Point"
        },
        "properties":{
          "city":"Jordan",
          "count":1,
          "deaths":0,
          "description":"<strong>Jordan</strong><p>Incidents: 1<br>Deaths: 0</p>",
          "icon":"theatre"
        },
        "type":"Feature"
      },
      {
        "geometry":{
          "coordinates":[
            126.983333,
            37.55
          ],
          "type":"Point"
        },
        "properties":{
          "city":"South Korea",
          "count":7979,
          "deaths":67,
          "description":"<strong>South Korea</strong><p>Incidents: 7979<br>Deaths: 67</p>",
          "icon":"theatre"
        },
        "type":"Feature"
      },
      {
        "geometry":{
          "coordinates":[
            47.966667,
            29.366666666666667
          ],
          "type":"Point"
        },
        "properties":{
          "city":"Kuwait",
          "count":80,
          "deaths":0,
          "description":"<strong>Kuwait</strong><p>Incidents: 80<br>Deaths: 0</p>",
          "icon":"theatre"
        },
        "type":"Feature"
      },
      {
        "geometry":{
          "coordinates":[
            24.1,
            56.95
          ],
          "type":"Point"
        },
        "properties":{
          "city":"Latvia",
          "count":16,
          "deaths":0,
          "description":"<strong>Latvia</strong><p>Incidents: 16<br>Deaths: 0</p>",
          "icon":"theatre"
        },
        "type":"Feature"
      },
      {
        "geometry":{
          "coordinates":[
            35.5,
            33.86666666666667
          ],
          "type":"Point"
        },
        "properties":{
          "city":"Lebanon",
          "count":66,
          "deaths":0,
          "description":"<strong>Lebanon</strong><p>Incidents: 66<br>Deaths: 0</p>",
          "icon":"theatre"
        },
        "type":"Feature"
      },
      {
        "geometry":{
          "coordinates":[
            9.516667,
            47.13333333333333
          ],
          "type":"Point"
        },
        "properties":{
          "city":"Liechtenstein",
          "count":4,
          "deaths":0,
          "description":"<strong>Liechtenstein</strong><p>Incidents: 4<br>Deaths: 0</p>",
          "icon":"theatre"
        },
        "type":"Feature"
      },
      {
        "geometry":{
          "coordinates":[
            25.316667,
            54.68333333333333
          ],
          "type":"Point"
        },
        "properties":{
          "city":"Lithuania",
          "count":3,
          "deaths":0,
          "description":"<strong>Lithuania</strong><p>Incidents: 3<br>Deaths: 0</p>",
          "icon":"theatre"
        },
        "type":"Feature"
      },
      {
        "geometry":{
          "coordinates":[
            6.116667,
            49.6
          ],
          "type":"Point"
        },
        "properties":{
          "city":"Luxembourg",
          "count":26,
          "deaths":0,
          "description":"<strong>Luxembourg</strong><p>Incidents: 26<br>Deaths: 0</p>",
          "icon":"theatre"
        },
        "type":"Feature"
      },
      {
        "geometry":{
          "coordinates":[
            101.7,
            3.1666666666666665
          ],
          "type":"Point"
        },
        "properties":{
          "city":"Malaysia",
          "count":158,
          "deaths":0,
          "description":"<strong>Malaysia</strong><p>Incidents: 158<br>Deaths: 0</p>",
          "icon":"theatre"
        },
        "type":"Feature"
      },
      {
        "geometry":{
          "coordinates":[
            73.5,
            4.166666666666667
          ],
          "type":"Point"
        },
        "properties":{
          "city":"Maldives",
          "count":8,
          "deaths":0,
          "description":"<strong>Maldives</strong><p>Incidents: 8<br>Deaths: 0</p>",
          "icon":"theatre"
        },
        "type":"Feature"
      },
      {
        "geometry":{
          "coordinates":[
            14.5,
            35.88333333333333
          ],
          "type":"Point"
        },
        "properties":{
          "city":"Malta",
          "count":9,
          "deaths":0,
          "description":"<strong>Malta</strong><p>Incidents: 9<br>Deaths: 0</p>",
          "icon":"theatre"
        },
        "type":"Feature"
      },
      {
        "geometry":{
          "coordinates":[
            -99.133333,
            19.433333333333334
          ],
          "type":"Point"
        },
        "properties":{
          "city":"Mexico",
          "count":16,
          "deaths":0,
          "description":"<strong>Mexico</strong><p>Incidents: 16<br>Deaths: 0</p>",
          "icon":"theatre"
        },
        "type":"Feature"
      },
      {
        "geometry":{
          "coordinates":[
            28.85,
            47.0
          ],
          "type":"Point"
        },
        "properties":{
          "city":"Moldova",
          "count":6,
          "deaths":0,
          "description":"<strong>Moldova</strong><p>Incidents: 6<br>Deaths: 0</p>",
          "icon":"theatre"
        },
        "type":"Feature"
      },
      {
        "geometry":{
          "coordinates":[
            7.416667,
            43.733333333333334
          ],
          "type":"Point"
        },
        "properties":{
          "city":"Monaco",
          "count":1,
          "deaths":0,
          "description":"<strong>Monaco</strong><p>Incidents: 1<br>Deaths: 0</p>",
          "icon":"theatre"
        },
        "type":"Feature"
      },
      {
        "geometry":{
          "coordinates":[
            106.916667,
            47.916666666666664
          ],
          "type":"Point"
        },
        "properties":{
          "city":"Mongolia",
          "count":1,
          "deaths":0,
          "description":"<strong>Mongolia</strong><p>Incidents: 1<br>Deaths: 0</p>",
          "icon":"theatre"
        },
        "type":"Feature"
      },
      {
        "geometry":{
          "coordinates":[
            -6.816667,
            34.016666666666666
          ],
          "type":"Point"
        },
        "properties":{
          "city":"Morocco",
          "count":6,
          "deaths":1,
          "description":"<strong>Morocco</strong><p>Incidents: 6<br>Deaths: 1</p>",
          "icon":"theatre"
        },
        "type":"Feature"
      },
      {
        "geometry":{
          "coordinates":[
            85.316667,
            27.716666666666665
          ],
          "type":"Point"
        },
        "properties":{
          "city":"Nepal",
          "count":1,
          "deaths":0,
          "description":"<strong>Nepal</strong><p>Incidents: 1<br>Deaths: 0</p>",
          "icon":"theatre"
        },
        "type":"Feature"
      },
      {
        "geometry":{
          "coordinates":[
            4.916667,
            52.35
          ],
          "type":"Point"
        },
        "properties":{
          "city":"Netherlands",
          "count":614,
          "deaths":5,
          "description":"<strong>Netherlands</strong><p>Incidents: 614<br>Deaths: 5</p>",
          "icon":"theatre"
        },
        "type":"Feature"
      },
      {
        "geometry":{
          "coordinates":[
            174.783333,
            -41.3
          ],
          "type":"Point"
        },
        "properties":{
          "city":"New Zealand",
          "count":5,
          "deaths":0,
          "description":"<strong>New Zealand</strong><p>Incidents: 5<br>Deaths: 0</p>",
          "icon":"theatre"
        },
        "type":"Feature"
      },
      {
        "geometry":{
          "coordinates":[
            7.533333,
            9.083333333333334
          ],
          "type":"Point"
        },
        "properties":{
          "city":"Nigeria",
          "count":2,
          "deaths":0,
          "description":"<strong>Nigeria</strong><p>Incidents: 2<br>Deaths: 0</p>",
          "icon":"theatre"
        },
        "type":"Feature"
      },
      {
        "geometry":{
          "coordinates":[
            10.75,
            59.916666666666664
          ],
          "type":"Point"
        },
        "properties":{
          "city":"Norway",
          "count":621,
          "deaths":1,
          "description":"<strong>Norway</strong><p>Incidents: 621<br>Deaths: 1</p>",
          "icon":"theatre"
        },
        "type":"Feature"
      },
      {
        "geometry":{
          "coordinates":[
            58.583333,
            23.616666666666667
          ],
          "type":"Point"
        },
        "properties":{
          "city":"Oman",
          "count":18,
          "deaths":0,
          "description":"<strong>Oman</strong><p>Incidents: 18<br>Deaths: 0</p>",
          "icon":"theatre"
        },
        "type":"Feature"
      },
      {
        "geometry":{
          "coordinates":[
            73.05,
            33.68333333333333
          ],
          "type":"Point"
        },
        "properties":{
          "city":"Pakistan",
          "count":21,
          "deaths":0,
          "description":"<strong>Pakistan</strong><p>Incidents: 21<br>Deaths: 0</p>",
          "icon":"theatre"
        },
        "type":"Feature"
      },
      {
        "geometry":{
          "coordinates":[
            -79.533333,
            8.966666666666667
          ],
          "type":"Point"
        },
        "properties":{
          "city":"Panama",
          "count":27,
          "deaths":1,
          "description":"<strong>Panama</strong><p>Incidents: 27<br>Deaths: 1</p>",
          "icon":"theatre"
        },
        "type":"Feature"
      },
      {
        "geometry":{
          "coordinates":[
            -57.666667,
            -25.266666666666666
          ],
          "type":"Point"
        },
        "properties":{
          "city":"Paraguay",
          "count":6,
          "deaths":0,
          "description":"<strong>Paraguay</strong><p>Incidents: 6<br>Deaths: 0</p>",
          "icon":"theatre"
        },
        "type":"Feature"
      },
      {
        "geometry":{
          "coordinates":[
            -77.05,
            -12.05
          ],
          "type":"Point"
        },
        "properties":{
          "city":"Peru",
          "count":22,
          "deaths":0,
          "description":"<strong>Peru</strong><p>Incidents: 22<br>Deaths: 0</p>",
          "icon":"theatre"
        },
        "type":"Feature"
      },
      {
        "geometry":{
          "coordinates":[
            120.966667,
            14.6
          ],
          "type":"Point"
        },
        "properties":{
          "city":"Philippines",
          "count":52,
          "deaths":2,
          "description":"<strong>Philippines</strong><p>Incidents: 52<br>Deaths: 2</p>",
          "icon":"theatre"
        },
        "type":"Feature"
      },
      {
        "geometry":{
          "coordinates":[
            21.0,
            52.25
          ],
          "type":"Point"
        },
        "properties":{
          "city":"Poland",
          "count":49,
          "deaths":1,
          "description":"<strong>Poland</strong><p>Incidents: 49<br>Deaths: 1</p>",
          "icon":"theatre"
        },
        "type":"Feature"
      },
      {
        "geometry":{
          "coordinates":[
            -9.133333,
            38.71666666666667
          ],
          "type":"Point"
        },
        "properties":{
          "city":"Portugal",
          "count":78,
          "deaths":0,
          "description":"<strong>Portugal</strong><p>Incidents: 78<br>Deaths: 0</p>",
          "icon":"theatre"
        },
        "type":"Feature"
      },
      {
        "geometry":{
          "coordinates":[
            51.533333,
            25.283333333333335
          ],
          "type":"Point"
        },
        "properties":{
          "city":"Qatar",
          "count":262,
          "deaths":0,
          "description":"<strong>Qatar</strong><p>Incidents: 262<br>Deaths: 0</p>",
          "icon":"theatre"
        },
        "type":"Feature"
      },
      {
        "geometry":{
          "coordinates":[
            26.1,
            44.43333333333333
          ],
          "type":"Point"
        },
        "properties":{
          "city":"Romania",
          "count":64,
          "deaths":0,
          "description":"<strong>Romania</strong><p>Incidents: 64<br>Deaths: 0</p>",
          "icon":"theatre"
        },
        "type":"Feature"
      },
      {
        "geometry":{
          "coordinates":[
            37.6,
            55.75
          ],
          "type":"Point"
        },
        "properties":{
          "city":"Russia",
          "count":34,
          "deaths":0,
          "description":"<strong>Russia</strong><p>Incidents: 34<br>Deaths: 0</p>",
          "icon":"theatre"
        },
        "type":"Feature"
      },
      {
        "geometry":{
          "coordinates":[
            -61.216667,
            13.133333333333333
          ],
          "type":"Point"
        },
        "properties":{
          "city":"Saint Vincent and the Grenadines",
          "count":1,
          "deaths":0,
          "description":"<strong>Saint Vincent and the Grenadines</strong><p>Incidents: 1<br>Deaths: 0</p>",
          "icon":"theatre"
        },
        "type":"Feature"
      },
      {
        "geometry":{
          "coordinates":[
            12.416667,
            43.93333333333333
          ],
          "type":"Point"
        },
        "properties":{
          "city":"San Marino",
          "count":67,
          "deaths":5,
          "description":"<strong>San Marino</strong><p>Incidents: 67<br>Deaths: 5</p>",
          "icon":"theatre"
        },
        "type":"Feature"
      },
      {
        "geometry":{
          "coordinates":[
            46.7,
            24.65
          ],
          "type":"Point"
        },
        "properties":{
          "city":"Saudi Arabia",
          "count":62,
          "deaths":0,
          "description":"<strong>Saudi Arabia</strong><p>Incidents: 62<br>Deaths: 0</p>",
          "icon":"theatre"
        },
        "type":"Feature"
      },
      {
        "geometry":{
          "coordinates":[
            -17.633333,
            14.733333333333333
          ],
          "type":"Point"
        },
        "properties":{
          "city":"Senegal",
          "count":6,
          "deaths":0,
          "description":"<strong>Senegal</strong><p>Incidents: 6<br>Deaths: 0</p>",
          "icon":"theatre"
        },
        "type":"Feature"
      },
      {
        "geometry":{
          "coordinates":[
            20.5,
            44.833333333333336
          ],
          "type":"Point"
        },
        "properties":{
          "city":"Serbia",
          "count":24,
          "deaths":0,
          "description":"<strong>Serbia</strong><p>Incidents: 24<br>Deaths: 0</p>",
          "icon":"theatre"
        },
        "type":"Feature"
      },
      {
        "geometry":{
          "coordinates":[
            103.85,
            1.2833333333333332
          ],
          "type":"Point"
        },
        "properties":{
          "city":"Singapore",
          "count":187,
          "deaths":0,
          "description":"<strong>Singapore</strong><p>Incidents: 187<br>Deaths: 0</p>",
          "icon":"theatre"
        },
        "type":"Feature"
      },
      {
        "geometry":{
          "coordinates":[
            17.116667,
            48.15
          ],
          "type":"Point"
        },
        "properties":{
          "city":"Slovakia",
          "count":21,
          "deaths":0,
          "description":"<strong>Slovakia</strong><p>Incidents: 21<br>Deaths: 0</p>",
          "icon":"theatre"
        },
        "type":"Feature"
      },
      {
        "geometry":{
          "coordinates":[
            14.516667,
            46.05
          ],
          "type":"Point"
        },
        "properties":{
          "city":"Slovenia",
          "count":96,
          "deaths":0,
          "description":"<strong>Slovenia</strong><p>Incidents: 96<br>Deaths: 0</p>",
          "icon":"theatre"
        },
        "type":"Feature"
      },
      {
        "geometry":{
          "coordinates":[
            28.216667,
            -25.7
          ],
          "type":"Point"
        },
        "properties":{
          "city":"South Africa",
          "count":17,
          "deaths":0,
          "description":"<strong>South Africa</strong><p>Incidents: 17<br>Deaths: 0</p>",
          "icon":"theatre"
        },
        "type":"Feature"
      },
      {
        "geometry":{
          "coordinates":[
            -3.683333,
            40.4
          ],
          "type":"Point"
        },
        "properties":{
          "city":"Spain",
          "count":3004,
          "deaths":84,
          "description":"<strong>Spain</strong><p>Incidents: 3004<br>Deaths: 84</p>",
          "icon":"theatre"
        },
        "type":"Feature"
      },
      {
        "geometry":{
          "coordinates":[
            79.833333,
            6.916666666666667
          ],
          "type":"Point"
        },
        "properties":{
          "city":"Sri Lanka",
          "count":3,
          "deaths":0,
          "description":"<strong>Sri Lanka</strong><p>Incidents: 3<br>Deaths: 0</p>",
          "icon":"theatre"
        },
        "type":"Feature"
      },
      {
        "geometry":{
          "coordinates":[
            18.05,
            59.333333333333336
          ],
          "type":"Point"
        },
        "properties":{
          "city":"Sweden",
          "count":620,
          "deaths":1,
          "description":"<strong>Sweden</strong><p>Incidents: 620<br>Deaths: 1</p>",
          "icon":"theatre"
        },
        "type":"Feature"
      },
      {
        "geometry":{
          "coordinates":[
            7.466667,
            46.916666666666664
          ],
          "type":"Point"
        },
        "properties":{
          "city":"Switzerland",
          "count":854,
          "deaths":4,
          "description":"<strong>Switzerland</strong><p>Incidents: 854<br>Deaths: 4</p>",
          "icon":"theatre"
        },
        "type":"Feature"
      },
      {
        "geometry":{
          "coordinates":[
            121.516667,
            25.033333333333335
          ],
          "type":"Point"
        },
        "properties":{
          "city":"Taiwan",
          "count":49,
          "deaths":1,
          "description":"<strong>Taiwan</strong><p>Incidents: 49<br>Deaths: 1</p>",
          "icon":"theatre"
        },
        "type":"Feature"
      },
      {
        "geometry":{
          "coordinates":[
            100.516667,
            13.75
          ],
          "type":"Point"
        },
        "properties":{
          "city":"Thailand",
          "count":70,
          "deaths":1,
          "description":"<strong>Thailand</strong><p>Incidents: 70<br>Deaths: 1</p>",
          "icon":"theatre"
        },
        "type":"Feature"
      },
      {
        "geometry":{
          "coordinates":[
            1.216667,
            6.116666666666666
          ],
          "type":"Point"
        },
        "properties":{
          "city":"Togo",
          "count":1,
          "deaths":0,
          "description":"<strong>Togo</strong><p>Incidents: 1<br>Deaths: 0</p>",
          "icon":"theatre"
        },
        "type":"Feature"
      },
      {
        "geometry":{
          "coordinates":[
            -61.516667,
            10.65
          ],
          "type":"Point"
        },
        "properties":{
          "city":"Trinidad and Tobago",
          "count":1,
          "deaths":0,
          "description":"<strong>Trinidad and Tobago</strong><p>Incidents: 1<br>Deaths: 0</p>",
          "icon":"theatre"
        },
        "type":"Feature"
      },
      {
        "geometry":{
          "coordinates":[
            10.183333,
            36.8
          ],
          "type":"Point"
        },
        "properties":{
          "city":"Tunisia",
          "count":13,
          "deaths":0,
          "description":"<strong>Tunisia</strong><p>Incidents: 13<br>Deaths: 0</p>",
          "icon":"theatre"
        },
        "type":"Feature"
      },
      {
        "geometry":{
          "coordinates":[
            32.866667,
            39.93333333333333
          ],
          "type":"Point"
        },
        "properties":{
          "city":"Turkey",
          "count":2,
          "deaths":0,
          "description":"<strong>Turkey</strong><p>Incidents: 2<br>Deaths: 0</p>",
          "icon":"theatre"
        },
        "type":"Feature"
      },
      {
        "geometry":{
          "coordinates":[
            30.516667,
            50.43333333333333
          ],
          "type":"Point"
        },
        "properties":{
          "city":"Ukraine",
          "count":3,
          "deaths":0,
          "description":"<strong>Ukraine</strong><p>Incidents: 3<br>Deaths: 0</p>",
          "icon":"theatre"
        },
        "type":"Feature"
      },
      {
        "geometry":{
          "coordinates":[
            54.366667,
            24.466666666666665
          ],
          "type":"Point"
        },
        "properties":{
          "city":"United Arab Emirates",
          "count":85,
          "deaths":0,
          "description":"<strong>United Arab Emirates</strong><p>Incidents: 85<br>Deaths: 0</p>",
          "icon":"theatre"
        },
        "type":"Feature"
      },
      {
        "geometry":{
          "coordinates":[
            -0.083333,
            51.5
          ],
          "type":"Point"
        },
        "properties":{
          "city":"United Kingdom",
          "count":373,
          "deaths":6,
          "description":"<strong>United Kingdom</strong><p>Incidents: 373<br>Deaths: 6</p>",
          "icon":"theatre"
        },
        "type":"Feature"
      },
      {
        "geometry":{
          "coordinates":[
            -77.0,
            38.883333
          ],
          "type":"Point"
        },
        "properties":{
          "city":"United States of America",
          "count":1663,
          "deaths":40,
          "description":"<strong>United States of America</strong><p>Incidents: 1663<br>Deaths: 40</p>",
          "icon":"theatre"
        },
        "type":"Feature"
      }
    ]
      return {"data": data, "stats": undefined}
}